# Generated by Django 2.2.4 on 2019-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='wiki',
            field=models.URLField(default='', max_length=250),
        ),
    ]
