# Generated by Django 2.2.4 on 2019-08-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20190823_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeIngredients',
        ),
        migrations.DeleteModel(
            name='IngrQuantity',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
