# Generated by Django 2.2.4 on 2019-08-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20190823_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngrQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('recipe_yield', models.IntegerField()),
                ('recipeIngredients', models.ManyToManyField(through='ingredients.IngrQuantity', to='ingredients.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingrquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Recipe'),
        ),
    ]
