# Generated by Django 2.2.4 on 2019-08-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_auto_20190828_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIngrQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('recipe_yield', models.IntegerField()),
                ('instructions', models.TextField(default='')),
                ('recipeIngredients', models.ManyToManyField(related_name='baserec_ingredients', through='ingredients.BaseIngrQuantity', to='ingredients.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='baseingrquantity',
            name='baseRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.BaseRecipe'),
        ),
        migrations.AddField(
            model_name='baseingrquantity',
            name='ingr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient'),
        ),
    ]
