# Generated by Django 2.2.4 on 2019-08-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_auto_20190828_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserecipe',
            name='yield_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient_Unit'),
        ),
    ]
