# Generated by Django 2.2.4 on 2019-08-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_baserecipe_yield_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserecipe',
            name='yield_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient_Unit'),
        ),
    ]
