# Generated by Django 2.2.4 on 2019-08-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_auto_20190828_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserecipe',
            name='recipe_yield',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='baserecipe',
            name='yield_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient_Unit'),
        ),
    ]
