# Generated by Django 2.2.4 on 2019-08-28 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_auto_20190828_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRecipeQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('baserecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.BaseRecipe')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeBaseRecipes',
            field=models.ManyToManyField(related_name='recBaseRec', through='ingredients.BaseRecipeQuantity', to='ingredients.BaseRecipe'),
        ),
    ]
