# Generated by Django 2.2.4 on 2019-08-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_auto_20190828_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientunit',
            old_name='unit',
            new_name='unitName',
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='unitSymbol',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
