# Generated by Django 2.2.4 on 2019-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_auto_20190828_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('wiki', models.URLField(default=None, max_length=250)),
                ('unit', models.ManyToManyField(to='ingredients.IngredientUnit')),
            ],
        ),
    ]
