# Generated by Django 2.2.4 on 2019-08-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0018_auto_20190829_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserecipe',
            name='brec_yield_unit',
        ),
        migrations.AddField(
            model_name='baserecipe',
            name='brec_yield_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseRecipes', to='ingredients.IngredientUnit'),
            preserve_default=False,
        ),
    ]
