# Generated by Django 2.2.4 on 2019-09-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0019_auto_20190829_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserec_ingredient_amount',
            name='ingredientUnit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_amount', to='ingredients.IngredientUnit'),
            preserve_default=False,
        ),
    ]
