# Generated by Django 2.2.4 on 2019-09-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0020_baserec_ingredient_amount_ingredientunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserec_ingredient_amount',
            name='ingredientUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.IngredientUnit'),
        ),
    ]
