# Generated by Django 2.2.4 on 2019-09-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0021_auto_20190901_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_bRec_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('brec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brec_amount', to='ingredients.BaseRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='Rec_Ingredient_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_ingredient_amount', to='ingredients.Ingredient')),
                ('ingredientUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.IngredientUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='baserec_ingredient_amount',
            name='baseRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brec_ingredient_amount', to='ingredients.BaseRecipe'),
        ),
        migrations.AlterField(
            model_name='baserec_ingredient_amount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brec_ingredient_amount', to='ingredients.Ingredient'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('recipe_yield', models.IntegerField()),
                ('procedure', models.TextField()),
                ('recipeBaseRecipes', models.ManyToManyField(related_name='recBaseRec', through='ingredients.Rec_bRec_Amount', to='ingredients.BaseRecipe')),
                ('recipeIngredients', models.ManyToManyField(related_name='rec_ingredients', through='ingredients.Rec_Ingredient_Amount', to='ingredients.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='rec_ingredient_amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_ingredient_amount', to='ingredients.Recipe'),
        ),
        migrations.AddField(
            model_name='rec_brec_amount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brec_amount', to='ingredients.Recipe'),
        ),
    ]
